version: "3.9"
services:
  base:
    image: ghcr.io/duderamos/vigilant-broccoli:base-${BASE_VERSION}
    build:
      context: .
      target: base
      args:
        BUILDKIT_INLINE_CACHE: 1
      cache_from:
        - ghcr.io/duderamos/vigilant-broccoli:base-${BASE_VERSION}
  web-dev:
    build:
      context: .
      target: dev
      args:
        BASE_VERSION: ${BASE_VERSION}
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
      - gem_home:/usr/local/bundle
      - node_modules_home:/app/node_modules
  postgres:
    image: postgres:alpine3.14
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
volumes:
  gem_home:
  node_modules_home:
  db_data:
