version: "3.9"
services:
  base:
    image: ${IMAGE_NAME}:base-${BASE_VERSION}
    build:
      context: .
      target: base
      args:
        BUILDKIT_INLINE_CACHE: 1
        IMAGE_NAME: ${IMAGE_NAME}
      cache_from:
        - ${IMAGE_NAME}:base-${BASE_VERSION}
  web-dev:
    tty: true
    stdin_open: true
    env_file:
      - .env
    build:
      context: .
      target: dev
      args:
        BASE_VERSION: ${BASE_VERSION}
        IMAGE_NAME: ${IMAGE_NAME}
    command: bin/dev
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - gems:/usr/local/bundle
      - node_modules:/app/node_modules
    user: ${UID}
  web:
    build:
      context: .
      target: web
      args:
        BASE_VERSION: ${BASE_VERSION}
        IMAGE_NAME: ${IMAGE_NAME}
  postgres:
    image: postgres:alpine3.14
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: "trust"
volumes:
  db_data:
  gems:
  node_modules:
