version: "3.9"
services:
  base:
    image: ghcr.io/duderamos/vigilant-broccoli:base-${BASE_VERSION}
    build:
      context: .
      target: base
      args:
        BUILDKIT_INLINE_CACHE: 1
      cache_from:
        - ghcr.io/duderamos/vigilant-broccoli:base-${BASE_VERSION}
  web-dev:
    tty: true
    env_file:
      - .env
    build:
      context: .
      target: dev
      args:
        BASE_VERSION: ${BASE_VERSION}
    command: bin/dev
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
  postgres:
    image: postgres:alpine3.14
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
volumes:
  db_data:
